### ISSUE TITLE
docker化

### ISSUE THREAD

**Issue by makoto-sasaki** [digitalstage/ExpressPlate#2]
よかったらご活用くださいー。（PR贈ろうとしたらパーミッションがなかったので、issueにしました）

db.ts
```
export default {
  development: {
    username: 'user',
    password: 'password',
    database: 'database',
    host: 'mysql',
    port: 3306,
    dialect: 'mysql',
    timezone: '+09:00'
  },
```

TOPフォルダにdocker-compose.yml
```
version: "3"

services:

  mysql:
    container_name: expressplate_mysql
    build: 
      context: ./docker
      dockerfile: Dockerfile_mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - 13306:3306

  express:
    container_name: expressplate_express
    build: 
      context: ./docker
      dockerfile: Dockerfile_express
    ports: 
      - 1337:1337
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - "./:/www"
      - "/www/node_modules"
    stdin_open: true
```
docker/Dockerfile_express
```
FROM node:10

# 基本
ARG base_timezone="Asia/Tokyo"
ARG DEBIAN_FRONTEND=noninteractive

# 基本 ###################################
RUN apt-get update
RUN apt-get -y install apt-utils --no-install-recommends

# locale設定
RUN apt-get -y install locales
RUN locale-gen ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LC_CTYPE ja_JP.UTF-8
RUN localedef -f UTF-8 -i ja_JP ja_JP.utf8

# timezone設定
ENV TZ="${base_timezone}"

# npm ###################################
RUN npm install -g typescript

# ポート解放
EXPOSE 1337
```

docker/Dockerfile_mysql
```
FROM mysql:8

# 基本
ARG base_timezone="Asia/Tokyo"
# mysql
ARG dbpass="password"
ARG dbname="database"

# 基本 ###################################
# locale設定
ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8"

# timezone設定
ENV TZ="${base_timezone}"

# mysql ###################################
ENV MYSQL_ROOT_PASSWORD="${dbpass}"
RUN echo "create database ${dbname};" >> /docker-entrypoint-initdb.d/createdb.sql

# ポート解放
EXPOSE 3306
```
